export const rrcsErrorCodes = {
	0: 'Success',
	1: 'Transaction key invalid',
	2: 'Net address invalid',
	3: 'Node address invalid',
	4: 'Port address invalid',
	5: 'Slot no. invalid',
	6: 'Input Gain invalid',
	7: 'IP-address invalid',
	8: 'TCP-Port invalid',
	9: 'Label invalid',
	10: 'Conference position invalid',
	11: 'Operation failed, because Artist-network not connected',
	12: 'Operation failed, because route does not exist',
	13: 'Operation not possible, because gateway is standby',
	14: 'XML-RPC parameters wrong for this request',
	15: 'Invalid conference or conference not found',
	16: 'Invalid conference member or conference member not found',
	17: 'Invalid priority',
	18: 'Invalid GPIO number',
	19: 'Invalid gain value',
	20: 'Timeout',
	21: 'No permission',
	22: 'Object does not exist',
	23: 'No USB-dongle available',
	24: 'Port is not online',
	25: 'Object property not supported',
	26: 'Limit exceeded',
	99: 'Generic error',
}

export const configChangeExErrorCodes = {
	0: 'Success',
	1: 'Internal Application Error',
	2: 'Configuration unavailable / not (yet) loaded',
	3: 'Node address invalid',
	4: 'Port address invalid',
	5: 'Slot no. invalid',
	6: 'Input Gain invalid',
	7: 'IP-address invalid',
	8: 'TCP-Port invalid',
	9: 'Label invalid',
	10: 'Conference position invalid',
	11: 'Operation failed, because Artist-network not connected',
	12: 'Operation failed, because route does not exist',
	13: 'Operation not possible, because gateway is standby',
	14: 'XML-RPC parameters wrong for this request',
	15: 'Invalid conference or conference not found',
	16: 'Invalid conference member or conference member not found',
	17: 'Invalid priority',
	18: 'Invalid GPIO number',
	19: 'Invalid gain value',
	20: 'Timeout',
	21: 'No permission',
	22: 'Object does not exist',
	23: 'No USB-dongle available',
	24: 'Port is not online',
	25: 'Object property not supported',
	26: 'Limit exceeded',
	99: 'Generic error',
	101: 'XML member required / mandatory',
	102: 'XML member ambiguous',
	103: 'XML member invalid',
	104: 'XML member unknown',
	105: 'XML member value type boolean required',
	106: 'XML member value type int required',
	107: 'XML member value type struct required',
	108: 'XML member value type array required',
	109: 'XML member value type string required',
	110: 'XML member value invalid',
	111: 'XML member value out of range',
	201: 'Instruction unsupported with current configuration',
	202: 'Duplicate configuration object',
	203: 'Addressed configuration object invalid',
	204: 'Addressed configuration object unsupported',
	205: 'Address already in use in configuration',
	206: 'Configuration member unsupported',
	207: 'Configuration member ambiguous',
	208: 'Configuration value invalid',
	209: 'Configuration value already in use',
	401: 'Generic',
}
